sudo: false
cache:
  apt: true
  go: true
  directories:
  - $HOME/.cache
  - $HOME/bin
  - $HOME/gopath/pkg/mod
env:
  global:
    - GO111MODULE=on
    - "PATH=$PATH:$HOME/bin"
    - protoc_version=3.7.1
language: go
go: "1.15"

install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.31.0
  - ./script/install-protoc $protoc_version
script:
  - go mod tidy && git diff --exit-code
  - ./all.bash
before_cache: rm -f $HOME/.cache/go-build/log.txt
after_success: bash <(curl -s https://codecov.io/bash)
