language: go
go:
  - "1.10"
  - tip
cache:
  apt: true
  go: true
addons:
  apt:
env:
  matrix:
    - app=crc
    - app=display
    - app=display/lcd-test
    - app=head
    - app=i2c
    - app=i2c/i2c-test
    - app=mdb
script: ./all.bash $app
sudo: false
